services:
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpMyAdmin
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.docker/phpmyadmin/sessions:/var/lib/phpmyadmin/sessions
      - ./.docker/phpmyadmin/tmp:/var/lib/phpmyadmin/tmp
      - ./.docker/phpmyadmin/php.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ./.docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"

      - "traefik.http.routers.pma.rule=Host(`${PHPMYADMIN_SERVER_HOSTNAME:?required}`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls.certresolver=le-cloudflare"
      - "traefik.http.routers.pma.service=pma"

      # Services
      - "traefik.http.services.pma.loadbalancer.server.port=80"


networks:
  traefik-network:
    external: true
